CREATE TABLE "JobSWI" (
  "id" TEXT NOT NULL,
  "orgId" TEXT NOT NULL,
  "jobId" TEXT NOT NULL,
  "content" JSONB NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,

  CONSTRAINT "JobSWI_pkey" PRIMARY KEY ("id")
);

ALTER TABLE "JobSWI"
ADD CONSTRAINT "JobSWI_orgId_fkey" FOREIGN KEY ("orgId") REFERENCES "Org"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "JobSWI"
ADD CONSTRAINT "JobSWI_jobId_fkey" FOREIGN KEY ("jobId") REFERENCES "Job"("id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE UNIQUE INDEX "JobSWI_jobId_key" ON "JobSWI"("jobId");
CREATE INDEX "JobSWI_orgId_idx" ON "JobSWI"("orgId");
CREATE INDEX "JobSWI_jobId_idx" ON "JobSWI"("jobId");
